yatube/about/urls.py
# about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
    path('contact/', views.AboutContactView.as_view(), name='contact'),
]

yatube/posts/urls.py
# posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('group_list/', views.group_list, name = 'group_list'),
    path('group/<slug:slug>/', views.group_posts, name= 'group'),
    # Профайл пользователя
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # Создание записи
    path('create/', views.post_create, name='post_create'),
    # Изменеие записи
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    # Добавление поста
    path('posts/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    # Посты автора, на которого подписан
    path('follow/', views.follow_index, name='follow_index'), 
    # Подписаться на автора
    path('profile/<str:username>/follow/',views.profile_follow, name='profile_follow'),
    # Отподписаться от автора
    path('profile/<str:username>/unfollow/',views.profile_unfollow, name='profile_unfollow'),
]

yatube/users/urls.py
# users/urls.py
from django.urls import path
from . import views

from django.contrib.auth.views import LogoutView , LoginView

app_name = 'users'

urlpatterns = [
        # Регистрация
    path('signup/', views.SignUp.as_view(), name='signup'),
        # Выход
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'), name = 'logout'),
        # Авторизация / Вход
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
        
        # Смена пароля
    path('password_change/', LoginView.as_view(template_name='users/password_change_form.html'), name='password_change_form'),
        # Сообщение об успешном изменении пароля
    path('password_change/done/', LoginView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),
        
        # Восстановление пароля
    path('password_reset/', LoginView.as_view(template_name='users/password_reset_form.html'), name='password_reset_form'),
        # Сообщение об отправке ссылки для восстановления пароля
    path('password_reset/done/', LoginView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
        
        # Вход по ссылке для восстановления пароля
    path('reset/<uidb64>/<token>/', LoginView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'), 
        # Сообщение об успешном восстановлении пароля 
    path('reset/done/', LoginView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]          

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/footer.html
<!-- templates/includes/footer.html -->
<!DOCTYPE html> 
<html lang="ru">          
  <body>       
    <footer class="page-footer font-small blue border-top">
      <div class="footer-copyright text-center py-3">© {{ year }} Copyright 
        <p><span style="color:red">Ya</span>tube</p> 
      </div>    
    </footer>
  </body>
</html>

yatube/templates/includes/head.html
<!-- templates/includes/head.html -->
{% load static %}

<head>
  <meta charset="utf-8"> <!-- Кодировка сайта -->
  <!-- Сайт готов работать с мобильными устройствами -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Загружаем фав-иконки -->
  <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
  <meta name="msapplication-TileColor" content="#000"> 
  <meta name="theme-color" content="#ffffff">
  <!-- Подключен файл со стандартными стилями бустрап -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
  <!-- Подключение необходимых JS-файлов Bootstrap -->
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</head>

yatube/templates/includes/header.html
<!-- templates/includes/header.html -->
{% load static %}  
    
<header>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: lightskyblue">
      <div class="container">
        <a class="navbar-brand" href="{% url 'posts:index' %}">
          <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
          <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
          <span style="color:red">Ya</span>tube
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">    
          <ul class="nav nav-pills">
            {% with request.resolver_match.view_name as view_name %} 
            <li class="nav-item"> 
              <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" 
              href="{% url 'about:author' %}">
                Об авторе
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}"
               href="{% url 'about:tech' %}">
               Технологии
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if view_name  == 'about:contact' %}active{% endif %}"
               href="{% url 'about:contact' %}">
               Контакты
              </a>
            </li>
            {% endwith %}
            {% if user.is_authenticated %}
            {% with request.resolver_match.view_name as view_name %}
            <li class="nav-item"> 
              <a class="nav-link link-light {% if view_name  == 'posts:post_create' %}active{% endif %}"
              href="{% url 'posts:post_create' %}">
              Новая запись
             </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light {% if view_name  == 'users:password_change_form' %}active{% endif %}"
               href="{% url 'users:password_change_form' %}">
               Изменить пароль
              </a>
            </li>
            {% endwith %}
            <li class="nav-item"> 
              <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
            </li>
            <li>
              Пользователь: {{ user.username }}
            </li>
            {% else %}
            {% with request.resolver_match.view_name as view_name %}
            <li class="nav-item"> 
              <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}"
               href="{% url 'users:login' %}">
               Войти
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}"
              href="{% url 'users:signup' %}">
              Регистрация
             </a>
            </li>
            {% endwith %}
            {% endif %}
          </ul>
          {# Конец добавленого в спринте #}
        </div>
      </div>
    </nav>  
</header>