yatube/about/urls.py
# about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
    path('contact/', views.AboutContactView.as_view(), name='contact'),
]

yatube/posts/urls.py
# posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('group_list/', views.group_list, name = 'group_list'),
    path('group/<slug:slug>/', views.group_posts, name= 'group'),
    # Профайл пользователя
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # Создание записи
    path('create/', views.post_create, name='post_create'),
    # Изменеие записи
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    # Добавление поста
    path('posts/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    # Посты автора, на которого подписан
    path('follow/', views.follow_index, name='follow_index'), 
    # Подписаться на автора
    path('profile/<str:username>/follow/',views.profile_follow, name='profile_follow'),
    # Отподписаться от автора
    path('profile/<str:username>/unfollow/',views.profile_unfollow, name='profile_unfollow'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from typing import Any
from django.db import models

from django.contrib.auth import get_user_model
from django.utils import timezone

User = get_user_model()

class Group(models.Model):
    title = models.CharField(
        max_length=100,
        verbose_name='Название группы')
    slug = models.SlugField(
        unique=True,
        verbose_name='Уникальный адрес группы')
    description = models.TextField(verbose_name='Описание сообщества')
    
    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title
    
    
class Post(models.Model):
    text = models.TextField(verbose_name="Полный текст поста",
                            help_text='Введите текст поста')
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name="Дата публикации",
                                    help_text='Дата, в которую опубликован пост')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name = "Автор",
        help_text='Выберете автора поста'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="Группа",
        help_text='Группа, к которой будет относиться пост')

    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )
    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        
    def __str__(self):
        return self.text[:15] 
    
    
class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name="Пост",
        help_text="Пост, к которому относится комментарий"
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name="Автор",
        help_text="Автор комментария"
    )
    text = models.TextField(
        verbose_name="Текст комментария",
        help_text="Введите текст комментария"
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата публикации",
        help_text="Дата и время публикации комментария"
    )

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Коментарий'
        verbose_name_plural = 'Коментарии'
        
    def __str__(self):
        return self.text[:15] 
    

    
class Follow(models.Model):
    # объект пользователя, который подписывается
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name="Подписчик",
        help_text="Подписчик на автора"
    )
    # объект пользователя, на которого подписываются
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name = "Автор",
        help_text='Автора поста'
    )

    # class Meta:
    #     ordering = ('-created',)
    #     verbose_name = 'Подписка'
    #     verbose_name_plural = 'Подписки'
        
    # def __str__(self):
    #     return self.text[:15] 

yatube/posts/forms.py
from django import forms
from .models import Post, Comment

#  создадим собственный класс для формы создания записи
#  сделаем его наследником предустановленного класса ModelForm
class PostForm(forms.ModelForm):
    class Meta():
        # укажем модель, с которой связана создаваемая форма
        model = Post
        # укажем, какие поля должны быть видны в форме и в каком порядке
        fields = ('text', 'group', 'image')
        
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Введите текст', 'style': 'border: 2px solid #ccc;'}),
            'group': forms.Select(attrs={'class': 'form-control', 'style': 'border: 2px solid #ccc; padding: 15px;'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control', 'accept': 'image/*', 'style': 'border: 2px solid #ccc; padding: 15px;', 'title': 'Загрузите ваше изображение здесь'}),
        }  
        
class CommentForm(forms.ModelForm):
    class Meta():
        # укажем модель, с которой связана создаваемая форма
        model = Comment
        # укажем, какие поля должны быть видны в форме и в каком порядке
        fields = ('text',)

yatube/posts/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Group, Comment, Follow

from django.views.generic.edit import CreateView
from .forms import PostForm, CommentForm

from django.views.decorators.cache import cache_page

from django.contrib.auth import get_user_model

from django.contrib.auth.decorators import login_required

User = get_user_model()

# кэш на 15 минут
# @cache_page(60 * 15)
def index(request):
    template = 'posts/index.html'
    title_index = "Главная страница"
    post_list = Post.objects.order_by('-pub_date')[:20]
    
    posts_all_count = Post.objects.count()
    
    # Показывать по 10 записей на странице.
    paginator = Paginator(post_list, 10) 
    
    # Из URL извлекаем номер запрошенной страницы - это значение параметра page
    page_number = request.GET.get('page')
    
    # Получаем набор записей для страницы с запрошенным номером
    page_obj = paginator.get_page(page_number)
    
    context = {
        'posts_all_count' : posts_all_count,
        'page_obj': page_obj,
        'title_index' : title_index,    
        'index': True,    
    }
    return render(request, template, context)  


def group_list(request):
    template = 'posts/group_list.html'
    title = "Список групп"
    groups = Group.objects.all()
    context = {
        'title': title,
        'groups' : groups
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_posts.html'
    title = "Список постов в группе"
    group = get_object_or_404(Group, slug=slug)    
 
    # Метод .filter позволяет ограничить поиск по критериям.
    # Это аналог добавления
    # условия WHERE group_id = {group_id}
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    
    paginator = Paginator(posts, 5)
    page_number = request.GET.get('page') 
    page_obj = paginator.get_page(page_number)
    
    context = {
        'page_obj': page_obj,  
        'title': title,
        'group': group,
    }
    return render(request, template, context)


def profile(request, username):
    # Здесь код запроса к модели и создание словаря контекста
    template = 'posts/profile.html'
    title = "Профайл пользователя" 

    author_posts = get_object_or_404(User, username=username) 
    # Подписан ли пользователь request.user на автора постов в профайле author_posts
    following = Follow.objects.filter(user=request.user, author=author_posts).exists()

    posts_count = Post.objects.filter(author=author_posts).count()
        
    post_list = Post.objects.filter(author=author_posts).order_by('-pub_date')
    
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    
    # Получаем набор записей для страницы с запрошенным номером
    page_obj = paginator.get_page(page_number)
   
    context = {
        'title': title,
        'page_obj' : page_obj,
        'posts_count' : posts_count,
        'author_posts' : author_posts,
        'following' : following,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, id = post_id)
    title = post.text[:30]
    number = Post.objects.filter(author=post.author).count()
    
    form = CommentForm()
    comments = Comment.objects.filter(post=post_id)

    context = {
        'number':number,
        'title': title,
        'post' : post,
        'form' : form,
        'comments' : comments,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/post_create.html'
    
    if request.method == 'POST':
        form = PostForm(request.POST, files=request.FILES or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', username=request.user.username)
        else:
            return render(request, template, {'form': form})
    else:
        form = PostForm()
        return render(request, template, {'form': form})


@login_required
def post_edit(request, post_id):
    template = 'posts/post_create.html'
        
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post.id)
   
    if request.method == 'POST':
        form = PostForm(request.POST , files=request.FILES or None, instance=post)

        if form.is_valid():
            form.save()
            return redirect('posts:post_detail', post_id=post.id)
        else:
            return render(request, template, {'form': form})
    else:
        
        form = PostForm(instance=post)
        context = {
        'post':post,
        'form':form,
        'is_edit': True,
    }
        return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id) 


@login_required
def follow_index(request):
    template = 'posts/follow.html'
    title_follow = "Страница постов авторов, на которых вы подписаны"
    
    # Получаем список авторов, на которых подписан текущий пользователь
    authors = Follow.objects.filter(user=request.user).values_list('author', flat=True)
    
    # Получаем посты только от этих авторов
    posts = Post.objects.filter(author__in=authors).order_by('-pub_date')
    
    paginator = Paginator(posts, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    context = {
        'title_follow': title_follow,
        'page_obj': page_obj,
        'follow': True, 
    }
    return render(request, template, context)



@login_required
def profile_follow(request, username):
    # Подписаться на автора
    author = get_object_or_404(User, username=username)

    # Проверяем, существует ли подписка, если нет - создаем
    Follow.objects.get_or_create(user=request.user, author=author)
    
    return redirect('posts:profile', username=username)



@login_required
def profile_unfollow(request, username):
    # Отписаться на автора
    author = get_object_or_404(User, username=username)

    Follow.objects.filter(user=request.user, author=author).delete()
    
    return redirect('posts:profile', username=username)

yatube/templates/posts/follow.html
<!-- templates/posts/follow.html Страница постов автора, на которого ты подписан-->
{% extends 'base.html' %}

{% load thumbnail %}

  {% block title %}
    <title>{{ title_follow }}</title>
  {% endblock %} 

  {% block header %}
    <div class="container py-4">
      <h2>Посты автора, на которого вы подписались</h2>
    </div>
  {% endblock %}

  {% block content %}
  {% include 'posts/includes/switcher.html' %}
    <div class="container py-1">      
      {% for post in page_obj %}
        {% include 'posts/includes/post_list.html' %}
             {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
    </div>
  {% endblock %} 

yatube/templates/posts/group_list.html
<!-- templates/posts/group_list.html -->
{% extends 'base.html' %}

    {% block title %}       
    <title>{{ title }}</title>
    {% endblock %}

      {% block content %}
      <div class="container py-3">
      <h2>Список Групп</h2>
      <p></p>
      <ul>
          {% for group in groups %}
              <li>{{ group.title }} - {{ group.description }}</li>
          {% empty %}
              <li>Нет доступных групп.</li>
          {% endfor %}
      </ul>
      {% endblock %}
      {% include 'posts/includes/paginator.html' %}

yatube/templates/posts/group_posts.html
<!-- templates/posts/group_posts.html -->
{% extends 'base.html' %}

{% load thumbnail %}

    {% block title %}       
    <title>{{ title }}</title>
    {% endblock %}

    {% block content %}
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">
        <h2>Список постов группы "{{group}}"</h2>
        {% for post in page_obj %}
            <div class="container py-1">
              <ul>
                <li>
                  Автор:
                  <a href="{% url 'posts:profile' post.author %}">
                    {{ post.author.get_full_name }}
                  </a> 
                </li>
                <li>
                  Дата публикации:{{ post.pub_date|date:"d E Y" }}
                </li>
                <li>
                {% if post.group %}
                   <p>Группа: {{ post.group.title }}
                   <a href="{% url 'posts:group_list' %}">Список  групп</a>
                  </p>
                {% else %}
                    <p>Группа: Нет</p>
                {% endif %}
                </li>
              </ul> 

              {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
              {% endthumbnail %}

                <b>Текст поста:</b> {{ post.text.title }}
                <p>
                  <a href="{% url 'posts:post_detail' post.id %}">
                    Подробная информация о посте
                  </a>
                </p>
               {% if not forloop.last %}<hr>{% endif %}
            </div>     
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
      </div>
      {% endblock %}

yatube/templates/posts/index.html
<!-- templates/posts/index.html Главная страница-->
{% extends 'base.html' %}

{% load thumbnail %}

  {% block title %}
    <title>{{ title_index  }}</title>
  {% endblock %} 

  {% block header %}
    <div class="container py-4">
      <h2>Последние обновления на сайте</h2>
    </div>
  {% endblock %}

    {% block content %}
      <div class="container py-1">      
        {% for post in page_obj %}

        {% include 'posts/includes/post_list.html' %}

           {% if post.group %}
             <a href="{% url 'posts:group' post.group.slug %}">
              Все записи группы: {{ post.group.title }}
             </a>
           {% endif %}
             {% if not forloop.last %}<hr>{% endif %}
          {% endfor %}
          <p>Всего постов на сайте:</b> {{posts_all_count}}</p>
         {% include 'posts/includes/paginator.html' %}
      </div>
    {% endblock %} 

yatube/templates/posts/post_create.html
<!-- templates/posts/post_create.html -->
{% extends 'base.html' %} 

{% block title %}
    {% if is_edit %}
        <title> Редактировать запись </title>
    {% else %}
        <title> Добавить запись </title>
    {% endif %} 
{% endblock %} 

{% block content %}
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-md-8 p-5">
                <div class="card">
                    <div class="card-header">
                        {% if is_edit %}
                            Редактировать пост
                        {% else %}
                            Новый пост
                        {% endif %}
                    </div>
                    <div class="card-body">
                        <form method="post" action="
                        {% if is_edit %}
                        {% url 'posts:post_edit' post.id %}

                        {% else %}
                        {% url 'posts:post_create' %}

                        {% endif %}"
                        
                        enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group row my-3 p-3">
                                <label for="id_text">
                                    Текст поста
                                    <span class="required text-danger">*</span>
                                </label>
                                {{ form.text }}
                                <small id="id_text-help" class="form-text text-muted">
                                    {% if is_edit %}
                                        Текст редактируемого поста
                                    {% else %}
                                        Текст нового поста
                                    {% endif %} 
                                </small>
                            </div>
                            <div class="form-group row my-3 p-3">
                                <label for="id_group">
                                    Группа
                                </label>
                                {{ form.group }}
                                <small id="id_group-help" class="form-text text-muted">
                                    Группа, к которой будет относиться пост
                                </small>
                            </div>

                            <div class="form-group row my-3 p-3">
                                <label for="id_image">
                                    Изображение
                                </label>
                                {{ form.image }}
                                <small id="id_group-help" class="form-text text-muted">
                                    Изображенние поста
                                </small>
                            </div>

                            <div class="d-flex justify-content-end">
                                <button type="submit" class="btn btn-primary">
                                    {% if is_edit %}
                                      Сохранить
                                    {% else %}
                                      Добавить
                                    {% endif %}               
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}  

yatube/templates/posts/post_detail.html
<!-- templates/posts/post_detail.html -->
{% extends 'base.html' %}

{% load thumbnail %}

{% block title %}
<title>Пост: {{title}} </title>
{% endblock %} 

{% block header %}
<div class="container py-4">
  <h2>Подробная информация о посте<h2>
</div>
{% endblock %}


{% block content %}
<div class="container py-1">
  <div class="row">  
    <aside class="col-12 col-md-6">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <b>Автор:</b> {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item">
          <b>Всего постов автора:</b> {{number}}
        </li>
        <li class="list-group-item">
          <b>Дата публикации:</b> {{ post.pub_date|date:"d E Y" }} г.
        </li>
        <li class="list-group-item">
          <b>Номер поста на сайте:</b> {{ post.id }}
        </li>
        {% if post.group %}   
        <li class="list-group-item">
          <b>Группа:</b> {{ post.group.title}}
          <p>
            <a href="{% url 'posts:group' post.group.slug %}">
              Все записи группы
            </a>
        </li>
        {% else %}
        <li class="list-group-item">
          <b>Группа:</b> Нет группы
        {% endif %}
        </li>
          </p>
      </ul>
    </aside>

    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    
    <div class="container py-1">
      <p>
        <b>Текст поста:</b> {{post.text}}
      </p>
      <p><a href="{% url 'posts:profile' post.author %}">
        Все посты пользователя
      </a>
      </p>
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
          Редактировать запись
        </a>  
    </div>


    {% load user_filters %}
    <div class="container py-1">
    {% if user.is_authenticated %}
      <div class="card my-4">
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
          <form method="post" action="{% url 'posts:add_comment' post.id %}">
            {% csrf_token %}      
            <div class="form-group mb-2">
              {{ form.text|addclass:"form-control" }}
                <small id="id_text-help" class="form-text text-muted">
                  {{form.text.help_text}}
                </small>
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
          </form>
        </div>
      </div>
    {% endif %}

    <h4 class="mt-0">
      <p>
        Комментарии:
      </p>
    </h4>

    {% for comment in comments %}
      <div class="media mb-4">
        <div class="media-body">
          <h5 class="mt-0">
            <a href="{% url 'posts:profile' comment.author.username %}">
              {{ comment.author.username }}
            </a>
          </h5>
          <p>
            {{ comment.text }}
          </p>
        </div>
      </div>
    {% endfor %} 

  </div>
</div> 
{% endblock %}

yatube/templates/posts/profile.html
<!-- templates/posts/profile.html -->
{% extends 'base.html' %}

{% load thumbnail %}

{% block title %}
  <title>{{ title }} {{ author_posts.get_full_name }}</title>
{% endblock %}

{% block header %}
<div class="container py-4">
  <h1>Все посты пользователя {{ author_posts.get_full_name }}</h1>
  <h3>Всего постов: {{ posts_count }}</h3>

  <!-- Добавляем условие, чтобы скрыть кнопки для собственного профиля -->
  {% if request.user != author_posts %}
    {% if following %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' author_posts.username %}" role="button"
      >
        Отписаться
      </a>
    {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author_posts.username %}" role="button"
      >
        Подписаться
      </a>
    {% endif %}
  {% endif %}
</div>
{% endblock %}

{% block content %}
  <div class="container py-1">      
    {% for post in page_obj %}
      {% include 'posts/includes/post_list.html' %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}